# Association Rule Learning (Apriori Algorithm)

In [1]:
! mkdir ~/.kaggle
! cp kaggle.json ~/.kaggle/
! chmod 600 ~/.kaggle/kaggle.json

mkdir: cannot create directory ‘/root/.kaggle’: File exists

In [2]:
!kaggle datasets download roshansharma/market-basket-optimization

Downloading market-basket-optimization.zip to /content
  0% 0.00/46.9k [00:00<?, ?B/s]
100% 46.9k/46.9k [00:00<00:00, 17.2MB/s]

In [3]:
!unzip market-basket-optimization.zip

Archive:  market-basket-optimization.zip
  inflating: Market_Basket_Optimisation.csv

In [4]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

In [5]:
df = pd.read_csv('Market_Basket_Optimisation.csv', header = None)

In [6]:
df.head()

              0          1           2   ...               17       18         19
0         shrimp    almonds     avocado  ...  frozen smoothie  spinach  olive oil
1        burgers  meatballs        eggs  ...              NaN      NaN        NaN
2        chutney        NaN         NaN  ...              NaN      NaN        NaN
3         turkey    avocado         NaN  ...              NaN      NaN        NaN
4  mineral water       milk  energy bar  ...              NaN      NaN        NaN

[5 rows x 20 columns]

In [7]:
all_transactions = []

for i in range(df.shape[0]):
    all_transactions.append([str(df.values[i, j]) for j in range(df.shape[1])])

In [8]:
t_encoder = TransactionEncoder()
encoded = t_encoder.fit_transform(all_transactions)
te_df = pd.DataFrame(encoded, columns = t_encoder.columns_)

In [9]:
te_df.head()

    asparagus  almonds  antioxydant juice  ...   yams  yogurt cake  zucchini
0       False     True               True  ...   True        False     False
1       False    False              False  ...  False        False     False
2       False    False              False  ...  False        False     False
3       False    False              False  ...  False        False     False
4       False    False              False  ...  False        False     False

[5 rows x 121 columns]

In [10]:
te_df.drop('nan', axis = 1, inplace = True)

In [11]:
rules = apriori(te_df, min_support = 0.02, max_len = 2, use_colnames = True)

In [12]:
rules['length'] = rules['itemsets'].apply(lambda x : len(x))

In [13]:
rules.head()

    support    itemsets  length
0  0.020397   (almonds)       1
1  0.033329   (avocado)       1
2  0.033729  (brownies)       1
3  0.087188   (burgers)       1
4  0.030129    (butter)       1

In [14]:
rules.drop(rules[rules['length'] == 1].index, axis = 0, inplace = True)

In [15]:
rules['LHS'] = rules['itemsets'].apply(lambda x : tuple(x)[0])
rules['RHS'] = rules['itemsets'].apply(lambda x : tuple(x)[1])

In [16]:
rules.drop(['itemsets', 'length'], axis = 1, inplace = True)

In [17]:
rules.reset_index(drop = True, inplace =True)

In [18]:
rules.head()

    support      LHS            RHS
0  0.028796  burgers           eggs
1  0.021997  burgers   french fries
2  0.024397  burgers  mineral water
3  0.021464  burgers      spaghetti
4  0.027463     cake  mineral water

<hr>